<a href="https://colab.research.google.com/github/bhavesh-choudhary1/machine_learning_concept/blob/main/Handling_Date_and_Time_VAriable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [ ]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [ ]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

##Working with Dates

In [ ]:
date['date'] = pd.to_datetime(date['date'])

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1.extract year

In [ ]:
date['date_year'] = date['date'].dt.year

In [ ]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

2.extract month

In [ ]:
date['date_month'] = date['date'].dt.month

In [ ]:
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

3.Extract Month name

In [ ]:
date['date_month_name'] = date['date'].dt.month_name()

In [ ]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

4.Extract Days

In [ ]:
date['date_day'] = date['date'].dt.day

In [ ]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

5.Extract Day of the week

In [ ]:
date['date_dow'] = date['date'].dt.dayofweek

In [ ]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

6.Day of week - name

In [ ]:
date['date_dow_name'] = date['date'].dt.day_name()

In [ ]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

7. is Weekend ?

In [ ]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)

In [ ]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

8. Extract week of the year

In [ ]:
date['date_week'] = date['date'].dt.isocalendar().week

In [ ]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

9. Extract Quater

In [ ]:
date['quater'] = date['date'].dt.quarter

In [ ]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quater
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

10. Extract Semester

In [ ]:
date['semester'] = np.where(date['quater'].isin([1,2]),1,2)

In [ ]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quater,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

11. Extract time elapsed between dates

In [ ]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2024, 12, 1, 12, 55, 53, 399369)

In [ ]:
today - date['date']

0     1818 days 12:55:53.399369
1     2300 days 12:55:53.399369
2     2231 days 12:55:53.399369
3     1933 days 12:55:53.399369
4     2156 days 12:55:53.399369
                 ...
995   2246 days 12:55:53.399369
996   2187 days 12:55:53.399369
997   2035 days 12:55:53.399369
998   2100 days 12:55:53.399369
999   1874 days 12:55:53.399369
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
(today - date['date']).dt.days

0      1818
1      2300
2      2231
3      1933
4      2156
       ...
995    2246
996    2187
997    2035
998    2100
999    1874
Name: date, Length: 1000, dtype: int64

In [ ]:
# month passed

np.round((today - date['date']) / np.timedelta64(1, 'M'),0)

ValueError: Unit M is not supported. Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'

In [ ]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [ ]:
time['date'] = pd.to_datetime(time['date'])

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [ ]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [ ]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extract Time Part

In [ ]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

Time Difference

In [ ]:
today - time['date']

0     4004 days 12:05:53.399369
1     3868 days 13:15:53.399369
2     4354 days 12:34:53.399369
3     3656 days 12:24:53.399369
4     4053 days 13:44:53.399369
                 ...
995   4643 days 12:05:53.399369
996   3964 days 13:41:53.399369
997   4429 days 13:18:53.399369
998   4545 days 13:21:53.399369
999   3817 days 13:30:53.399369
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
# in second

(today - time['date'])/np.timedelta64(1,'s')

0      3.459892e+08
1      3.342430e+08
2      3.762309e+08
3      3.159231e+08
4      3.502287e+08
           ...
995    4.011988e+08
996    3.425389e+08
997    3.827135e+08
998    3.927361e+08
999    3.298375e+08
Name: date, Length: 1000, dtype: float64

In [ ]:
# in minute

(today - time['date'])/np.timedelta64(1,'m')

0      5.766486e+06
1      5.570716e+06
2      6.270515e+06
3      5.265385e+06
4      5.837145e+06
           ...
995    6.686646e+06
996    5.708982e+06
997    6.378559e+06
998    6.545602e+06
999    5.497291e+06
Name: date, Length: 1000, dtype: float64

In [ ]:
# in hour

(today - time['date'])/np.timedelta64(1,'h')

0       96108.098166
1       92845.264833
2      104508.581500
3       87756.414833
4       97285.748166
           ...
995    111444.098166
996     95149.698166
997    106309.314833
998    109093.364833
999     91621.514833
Name: date, Length: 1000, dtype: float64